let cardArray = [
    {
      "Tarokka_Name": "Avenger",
      "Fortune": "The treasure lies in a dragon’s house, in hands once clean and now corrupted.",
      "Result": "The treasure is in the possession of Vladimir Horngaard in Argynvostholt (chapter 7, area Q36).",
      "Tarokka_Card_URL": "Avenger.jpg",
      "Rank": 1,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "AS.png",
      "Playing_Card_Suit": "Spade",
      "Index": 0,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Paladin",
      "Fortune": "I see a sleeping prince, a servant of light and the brother of darkness. The treasure lies with him.",
      "Result": "The treasure lies in Sergei’s tomb (chapter 4, area K85).",
      "Tarokka_Card_URL": "Paladin.jpg",
      "Rank": 2,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "2S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 1,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Soldier",
      "Fortune": "Go to the mountains. Climb the white tower guarded by golden knights.",
      "Result": "The treasure lies on the rooftop of the Tsolenka Pass guard tower (chapter 9, area T6).",
      "Tarokka_Card_URL": "Soldier.jpg",
      "Rank": 3,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "3S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 2,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Mercenary",
      "Fortune": "The thing you seek lies with the dead, under mountains of gold coins.",
      "Result": "The treasure lies in a crypt in Castle Ravenloft (chapter 4, area K84, crypt 31).",
      "Tarokka_Card_URL": "Mercenary.jpg",
      "Rank": 4,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "4S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 3,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Myrmidon",
      "Fortune": "Look for a den of wolves in the hills overlooking a mountain lake. The treasure belongs to Mother Night.",
      "Result": "The treasure lies in the shrine of Mother Night in the werewolf den (chapter 15, area Z7).",
      "Tarokka_Card_URL": "Myrmidon.jpg",
      "Rank": 5,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "5S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 4,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Berserker",
      "Fortune": "Find the Mad Dog’s crypt. The treasure lies within, beneath blackened bones.",
      "Result": "The treasure lies in the crypt of General Kroval “Mad Dog” Grislek (chapter 4, area K84, crypt 38).",
      "Tarokka_Card_URL": "Berserker.jpg",
      "Rank": 6,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "6S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 5,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Hooded One",
      "Fortune": "I see a faceless god. He awaits you at the end of a long and winding road, deep in the mountains.",
      "Result": "The treasure is inside the head of the giant statue in the Amber Temple (chapter 13, area X5a).",
      "Tarokka_Card_URL": "Hooded_One.jpg",
      "Rank": 7,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "7S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 6,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Dictator",
      "Fortune": "I see a throne fit for a king.",
      "Result": "The treasure lies in Castle Ravenloft’s audience hall (chapter 4, area K25).",
      "Tarokka_Card_URL": "Dictator.jpg",
      "Rank": 8,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "8S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 7,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Torturer",
      "Fortune": "There is a town where all is not well. There you will find a house of corruption, and within, a dark room full of still ghosts.",
      "Result": "The treasure is hidden in the attic of the burgomaster’s mansion in Vallaki (chapter 5, area N3s).",
      "Tarokka_Card_URL": "Torturer.jpg",
      "Rank": 9,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "9S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 8,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Warrior",
      "Fortune": "That which you seek lies in the womb of darkness, the devil’s lair: the one place to which he must return.",
      "Result": "The treasure lies in Strahd’s tomb (chapter 4, area K86).",
      "Tarokka_Card_URL": "Warrior.jpg",
      "Rank": 10,
      "Tarokka_Card_Suit": "Swords",
      "Playing_Card_URL": "10S.png",
      "Playing_Card_Suit": "Spade",
      "Index": 9,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Transmuter",
      "Fortune": "Go to a place of dizzying heights, where the stone itself is alive!",
      "Result": "The treasure lies in Castle Ravenloft’s north tower peak (chapter 4, area K60).",
      "Tarokka_Card_URL": "Transmuter.jpg",
      "Rank": 1,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "AC.png",
      "Playing_Card_Suit": "Club",
      "Index": 10,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Diviner",
      "Fortune": "Look to the one who sees all. The treasure is hidden in her camp.",
      "Result": "The treasure lies in Madam Eva’s encampment (chapter 2, area G). If she is the one performing the card reading, she says, “I think the treasure is under my very nose!”",
      "Tarokka_Card_URL": "Diviner.jpg",
      "Rank": 2,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "2C.png",
      "Playing_Card_Suit": "Club",
      "Index": 11,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Enchanter",
      "Fortune": "I see a kneeling woman — a rose of great beauty plucked too soon. The master of the marsh knows of whom I speak.",
      "Result": "The treasure lies under Marina’s monument in Berez (chapter 10, area U5). “The master of the marsh” refers to Burgomaster Lazlo Ulrich (area U2), whose ghost can point characters toward the monument.",
      "Tarokka_Card_URL": "Enchanter.jpg",
      "Rank": 3,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "3C.png",
      "Playing_Card_Suit": "Club",
      "Index": 12,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Abjurer",
      "Fortune": "I see a fallen house guarded by a great stone dragon. Look to the highest peak.",
      "Result": "The treasure lies in the beacon of Argynvostholt (chapter 7, area Q53). “Great stone dragon” refers to the statue in area Q1.",
      "Tarokka_Card_URL": "Abjurer.jpg",
      "Rank": 4,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "4C.png",
      "Playing_Card_Suit": "Club",
      "Index": 13,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Elementalist",
      "Fortune": "The treasure is hidden in a small castle beneath a mountain, guarded by amber giants.",
      "Result": "The treasure is inside a model of Castle Ravenloft in the Amber Temple (chapter 13, area X20).",
      "Tarokka_Card_URL": "Elementalist.jpg",
      "Rank": 5,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "5C.png",
      "Playing_Card_Suit": "Club",
      "Index": 14,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Evoker",
      "Fortune": "Search for the crypt of a wizard ordinaire. His staff is the key.",
      "Result": "The treasure is hidden in the crypt of Gralmore Nimblenobs (chapter 4, area K84, crypt 37).",
      "Tarokka_Card_URL": "Evoker.jpg",
      "Rank": 6,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "6C.png",
      "Playing_Card_Suit": "Club",
      "Index": 15,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Illusionist",
      "Fortune": "A man is not what he seems. He comes here in a carnival wagon. Therein lies what you seek.",
      "Result": "The treasure lies in Rictavio’s carnival wagon (chapter 5, area N5).",
      "Tarokka_Card_URL": "Illusionist.jpg",
      "Rank": 7,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "7C.png",
      "Playing_Card_Suit": "Club",
      "Index": 16,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Necromancer",
      "Fortune": "A woman hangs above a roaring fire. Find her, and you will find the treasure.",
      "Result": "The treasure lies in Castle Ravenloft’s study (chapter 4, area K37).",
      "Tarokka_Card_URL": "Necromancer.jpg",
      "Rank": 8,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "8C.png",
      "Playing_Card_Suit": "Club",
      "Index": 17,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Conjurer",
      "Fortune": "I see a dead village, drowned by a river, ruled by one who has brought great evil into the world.",
      "Result": "The treasure is in Baba Lysaga’s hut (chapter 10, area U3).",
      "Tarokka_Card_URL": "Conjurer.jpg",
      "Rank": 9,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "9C.png",
      "Playing_Card_Suit": "Club",
      "Index": 18,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Wizard",
      "Fortune": "Look for a wizard’s tower on a lake. Let the wizard’s name and servant guide you to that which you seek.",
      "Result": "The treasure lies on the top floor of Van Richten’s Tower (chapter 11, area V7).",
      "Tarokka_Card_URL": "Wizard.jpg",
      "Rank": 10,
      "Tarokka_Card_Suit": "Stars",
      "Playing_Card_URL": "10C.png",
      "Playing_Card_Suit": "Club",
      "Index": 19,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Swashbuckler",
      "Fortune": "I see the skeleton of a deadly warrior, lying on a bed of stone flanked by gargoyles.",
      "Result": "The treasure lies in the crypt of Endorovich (chapter 4, area K84, crypt 7)",
      "Tarokka_Card_URL": "Swashbuckler.jpg",
      "Rank": 1,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "AD.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 20,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Philanthropist",
      "Fortune": "Look to a place where sickness and madness are bred. Where children once cried, the treasure lies still.",
      "Result": "The treasure is in the nursery of the Abbey of Saint Markovia (chapter 8, area S23).",
      "Tarokka_Card_URL": "Philanthropist.jpg",
      "Rank": 2,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "2D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 21,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Trader",
      "Fortune": "Look to the wizard of wines! In wood and sand the treasure hides.",
      "Result": "The treasure lies in the glassblower’s workshop in the Wizard of Wines winery (chapter 12, area W10).",
      "Tarokka_Card_URL": "Trader.jpg",
      "Rank": 3,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "3D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 22,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Merchant",
      "Fortune": "Seek a cask that once contained the finest wine, of which not a drop remains.",
      "Result": "The treasure lies in Castle Ravenloft’s wine cellar (chapter 4, area K63).",
      "Tarokka_Card_URL": "Merchant.jpg",
      "Rank": 4,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "4D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 23,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Guild Member",
      "Fortune": "I see a dark room full of bottles. It is the tomb of a guild member.",
      "Result": "The treasure lies in the crypt of Artank Swilovich (chapter 4, area K84, crypt 5).",
      "Tarokka_Card_URL": "Guild_Member.jpg",
      "Rank": 5,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "5D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 24,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Beggar",
      "Fortune": "A wounded elf has what you seek. He will part with the treasure to see his dark dreams fulfilled.",
      "Result": "The treasure is hidden in Kasimir’s hovel (chapter 5, area N9a).",
      "Tarokka_Card_URL": "Beggar.jpg",
      "Rank": 6,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "6D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 25,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Thief",
      "Fortune": "What you seek lies at the crossroads of life and death, among the buried dead.",
      "Result": "The treasure is buried in the graveyard at the River Ivlis crossroads (chapter 2, area F).",
      "Tarokka_Card_URL": "Thief.jpg",
      "Rank": 7,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "7D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 26,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Tax Collector",
      "Fortune": "The Vistani have what you seek. A missing child holds the key to the treasure’s release.",
      "Result": "The treasure is hidden in the Vistani treasure wagon (chapter 5, area N9i). “A missing child” refers to Arabelle (see chapter 2, area L).",
      "Tarokka_Card_URL": "Tax_Collector.jpg",
      "Rank": 8,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "8D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 27,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Miser",
      "Fortune": "Look for a fortress inside a fortress, in a place hidden behind fire.",
      "Result": "The treasure lies in Castle Ravenloft’s treasury (chapter 4, area K41).",
      "Tarokka_Card_URL": "Miser.jpg",
      "Rank": 9,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "9D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 28,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Rogue",
      "Fortune": "I see a nest of ravens. There you will find the prize.",
      "Result": "The treasure is hidden in the attic of the Blue Water Inn (chapter 5, area N2q).",
      "Tarokka_Card_URL": "Rogue.jpg",
      "Rank": 10,
      "Tarokka_Card_Suit": "Coins",
      "Playing_Card_URL": "10D.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 29,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Monk",
      "Fortune": "The treasure you seek is hidden behind the sun, in the house of a saint.",
      "Result": "The treasure lies in the main hall of the Abbey of Saint Markovia (chapter 8, area S13).",
      "Tarokka_Card_URL": "Monk.jpg",
      "Rank": 1,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "AH.png",
      "Playing_Card_Suit": "Heart",
      "Index": 30,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Missionary",
      "Fortune": "I see a garden dusted with snow, watched over by a scarecrow with a sackcloth grin. Look not to the garden but to the guardian.",
      "Result": "The treasure is hidden inside one of the scarecrows in the garden of the Abbey of Saint Markovia (chapter 8, area S9).",
      "Tarokka_Card_URL": "Missionary.jpg",
      "Rank": 2,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "2H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 31,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Healer",
      "Fortune": "Look to the west. Find a pool blessed by the light of the white sun.",
      "Result": "The treasure lies beneath the gazebo in the Shrine of the White Sun (chapter 8, area S4).",
      "Tarokka_Card_URL": "Healer.jpg",
      "Rank": 3,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "3H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 32,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Shepherd",
      "Fortune": "Find the mother — she who gave birth to evil.",
      "Result": "The treasure lies in the tomb of King Barov and Queen Ravenovia (chapter 4, area K88).",
      "Tarokka_Card_URL": "Shepherd.jpg",
      "Rank": 4,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "4H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 33,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Druid",
      "Fortune": "An evil tree grows atop a hill of graves where the ancient dead sleep. The ravens can help you find it. Look for the treasure there.",
      "Result": "The treasure lies at the base of the Gulthias tree (chapter 14, area Y4). Any wereraven encountered in the wilderness can lead the characters to the location.",
      "Tarokka_Card_URL": "Druid.jpg",
      "Rank": 5,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "5H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 34,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Anarchist",
      "Fortune": "I see walls of bones, a chandelier of bones, and a table of bones — all that remains of enemies long forgotten.",
      "Result": "The treasure lies in Castle Ravenloft’s hall of bones (chapter 4, area K67).",
      "Tarokka_Card_URL": "Anarchist.jpg",
      "Rank": 6,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "6H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 35,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Charlatan",
      "Fortune": "I see a lonely mill on a precipice. The treasure lies within.",
      "Result": "The treasure lies in the attic of Old Bonegrinder (chapter 6, area O4).",
      "Tarokka_Card_URL": "Charlatan.jpg",
      "Rank": 7,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "7H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 36,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Bishop",
      "Fortune": "What you seek lies in a pile of treasure, beyond a set of amber doors.",
      "Result": "The treasure lies in the sealed treasury of the Amber Temple (chapter 13, area X40).",
      "Tarokka_Card_URL": "Bishop.jpg",
      "Rank": 8,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "8H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 37,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Traitor",
      "Fortune": "Look for a wealthy woman. A staunch ally of the devil, she keeps the treasure under lock and key, with the bones of an ancient enemy.",
      "Result": "The treasure is hidden in the master bedroom of Wachterhaus (chapter 5, area N4o).",
      "Tarokka_Card_URL": "Traitor.jpg",
      "Rank": 9,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "9H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 38,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Priest",
      "Fortune": "You will find what you seek in the castle, amid the ruins of a place of supplication.",
      "Result": "The treasure lies in Castle Ravenloft’s chapel (chapter 4, area K15).",
      "Tarokka_Card_URL": "Priest.jpg",
      "Rank": 10,
      "Tarokka_Card_Suit": "Glyphs",
      "Playing_Card_URL": "10H.png",
      "Playing_Card_Suit": "Heart",
      "Index": 39,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Ghost",
      "Fortune": "I see a fallen paladin of a fallen order of knights. He lingers like a ghost in a dead dragon’s lair.",
      "Result": "This card refers to the revenant Sir Godfrey Gwilym (see chapter 7, area Q37). Although initially unwilling to accompany the characters, he will do so if the characters convince him that the honor of the Order of the Silver Dragon can be restored with his help. Doing this requires a successful DC 15 Charisma (Persuasion) check.",
      "Tarokka_Card_URL": "Ghost.jpg",
      "Rank": 13,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "KH.png",
      "Playing_Card_Suit": "Heart",
      "Index": 40,
      "Fortune2": "Stir the spirit of the clumsy knight whose crypt lies deep within the castle.",
      "Result2": "This card refers to Sir Klutz the phantom warrior (see chapter 4, area K84, crypt 33). If Sir Klutz is Strahd’s enemy, then the phantom warrior disappears not after seven days, but only after he or Strahd is reduced to 0 hit points."
    },
    {
      "Tarokka_Name": "Innocent",
      "Fortune": "I see a young man with a kind heart. A mother’s boy! He is strong in body but weak of mind. Seek him out in the village of Barovia.",
      "Result": "This card refers to Parriwimple (see chapter 3, area E1). Although he’s a simpleton, he won’t travel to Castle Ravenloft without good cause. Characters can manipulate him into going by preying on his good heart. For instance, he might go there to help rescue missing Barovians, or to save the life of Ireena Kolyana, who is very beautiful. The characters must somehow deal with Bildrath, Parriwimple’s employer, who won’t let the foolish boy go to the castle for any reason.",
      "Tarokka_Card_URL": "Innocent.jpg",
      "Rank": 12,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "QH.png",
      "Playing_Card_Suit": "Heart",
      "Index": 41,
      "Fortune2": "Evil’s bride is the one you seek!",
      "Result2": "This card refers to Ireena Kolyana (see chapter 3, area E4). Her brother, Ismark, opposes the idea of Ireena’s being taken to Castle Ravenloft, but she insists on going there once the characters tell her about the card reading. Ireena won’t accompany the characters, however, until Kolyan Indirovich’s body is laid to rest in the cemetery."
    },
    {
      "Tarokka_Name": "Marionette",
      "Fortune": "What horror is this? I see a man made by a man. Ageless and alone, it haunts the towers of the castle.",
      "Result": "This card refers to Pidlwick II (see chapter 4, area K59, as well as appendix D).",
      "Tarokka_Card_URL": "Marionette.jpg",
      "Rank": 11,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "JH.png",
      "Playing_Card_Suit": "Heart",
      "Index": 42,
      "Fortune2": "Look for a man of music, a man with two heads. He lives in a place of great hunger and sorrow.",
      "Result2": "This card refers to Clovin Belview (see chapter 8, area S17), the two-headed mongrelfolk. Clovin serves the Abbot out of fear and a perverse sense of loyalty. His job is to deliver food to the other mongrelfolk, whom he abhors. If the Abbot still lives, Clovin doesn’t want to earn his master’s ire by attempting to leave, and he refuses to accompany the characters. But if the Abbot dies, Clovin doesn’t have any reason to remain in the abbey, so he’s willing to come along if he is bribed with wine. Clovin provides no benefit to the party without his viol."
    },
    {
      "Tarokka_Name": "Darklord",
      "Fortune": "Ah, the worst of all truths: You must face the evil of this land alone!",
      "Result": "There is no NPC who can inspire the characters.",
      "Tarokka_Card_URL": "Darklord.jpg",
      "Rank": 13,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "KS.png",
      "Playing_Card_Suit": "Spade",
      "Index": 43,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Mists",
      "Fortune": "A Vistana wanders this land alone, searching for her mentor. She does not stay in one place for long. Seek her out at Saint Markovia’s abbey, near the mists.",
      "Result": "This card refers to Ezmerelda d’Avenir (see appendix D). She can be found in the Abbey of Saint Markovia (see chapter 8, area S19), as well as several other locations throughout Barovia.",
      "Tarokka_Card_URL": "Mists.jpg",
      "Rank": 12,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "QS.png",
      "Playing_Card_Suit": "Spade",
      "Index": 44,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Executioner",
      "Fortune": "Seek out the brother of the devil’s bride. They call him “the lesser,” but he has a powerful soul.",
      "Result": "This card refers to Ismark Kolyanovich (see chapter 3, area E2). Ismark won’t accompany the characters to Castle Ravenloft until he knows that his sister, Ireena Kolyana, is safe.",
      "Tarokka_Card_URL": "Executioner.jpg",
      "Rank": 11,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "JS.png",
      "Playing_Card_Suit": "Spade",
      "Index": 45,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Donjon",
      "Fortune": "Search for a troubled young man surrounded by wealth and madness. His home is his prison.",
      "Result": "This card refers to Victor Vallakovich (see chapter 5, area N3t). Realizing that the characters are the key to his salvation, he enthusiastically leaves home and accompanies them to Castle Ravenloft.",
      "Tarokka_Card_URL": "Donjon.jpg",
      "Rank": 13,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "KC.png",
      "Playing_Card_Suit": "Club",
      "Index": 46,
      "Fortune2": "Find a girl driven to insanity, locked in the heart of her dead father’s house. Curing her madness is key to your success.",
      "Result2": "This card refers to Stella Wachter (see chapter 5, area N4n). She grants the party no benefit unless her madness is cured. With her wits restored, Stella is happy to join the party and leave her rotten family behind."
    },
    {
      "Tarokka_Name": "Raven",
      "Fortune": "Find the leader of the feathered ones who live among the vines. Though old, he has one more fight left in him.",
      "Result": "This card refers to Davian Martikov (see chapter 12, “The Wizard of Wines”). The old wereraven, realizing that he has a chance to end Strahd’s tyranny, leaves his vineyard and winery in the capable hands of his sons, Adrian and Elvir. But before he travels to Castle Ravenloft to face Strahd, Davian insists on reconciling with his third son, Urwin Martikov (see chapter 5, area N2).",
      "Tarokka_Card_URL": "Raven.jpg",
      "Rank": 12,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "QC.png",
      "Playing_Card_Suit": "Club",
      "Index": 47,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Seer",
      "Fortune": "Look for a dusk elf living among the Vistani. He has suffered a great loss and is haunted by dark dreams. Help him, and he will help you in return.",
      "Result": "This card refers to Kasimir Velikov (see chapter 5, area N9a). The dusk elf accompanies the characters to Castle Ravenloft only after they lead him to the Amber Temple and help him find the means to resurrect his dead sister, Patrina Velikovna.",
      "Tarokka_Card_URL": "Seer.jpg",
      "Rank": 11,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "JC.png",
      "Playing_Card_Suit": "Club",
      "Index": 48,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Broken One",
      "Fortune": "Your greatest ally will be a wizard. His mind is broken, but his spells are strong.",
      "Result": "This card refers to the Mad Mage of Mount Baratok (see chapter 2, area M).",
      "Tarokka_Card_URL": "Broken_One.jpg",
      "Rank": 13,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "KD.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 49,
      "Fortune2": "I see a man of faith whose sanity hangs by a thread. He has lost someone close to him.",
      "Result2": "This card refers to Donavich, the priest in the village of Barovia (see chapter 3, area E5). He will not accompany the characters until his son, Doru, is dead and buried."
    },
    {
      "Tarokka_Name": "Tempter",
      "Fortune": "I see a child — a Vistana. You must hurry, for her fate hangs in the balance. Find her at the lake!",
      "Result": "This card refers to Arabelle (see chapter 2, area L). She gladly joins the party. But if she returns to her camp (chapter 5, area N9), her father, Luvash, refuses to let her leave.",
      "Tarokka_Card_URL": "Tempter.jpg",
      "Rank": 12,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "QD.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 50,
      "Fortune2": "I hear a wedding bell, or perhaps a death knell. It calls thee to a mountainside abbey, wherein you will find a woman who is more than the sum of her parts.",
      "Result2": "This card refers to Vasilka the flesh golem (see chapter 8, area S13)."
    },
    {
      "Tarokka_Name": "Beast",
      "Fortune": "A werewolf holds a secret hatred for your enemy. Use her hatred to your advantage.",
      "Result": "This card refers to the werewolf Zuleika Toranescu (see chapter 15, area Z7). She will accompany the characters if they promise to avenge her mate, Emil, by killing the leader of her pack, Kiril Stoyanovich.",
      "Tarokka_Card_URL": "Beast.jpg",
      "Rank": 11,
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "JD.png",
      "Playing_Card_Suit": "Diamond",
      "Index": 51,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Artifact",
      "Fortune": "Look for an entertaining man with a monkey. This man is more than he seems.",
      "Result": "This card refers to Rictavio (see appendix D), who can be found at the Blue Water Inn in Vallaki (chapter 5, area N2). Normally reluctant to accompany the characters, Rictavio changes his tune if the characters tell him about the card reading. He sheds his disguise and introduces himself as Dr. Rudolph van Richten. The characters might think that Gadof Blinsky, the toymaker of Vallaki (area N7), is the figure they seek, because he has a pet monkey. If they speak to him about this possibility, Blinsky jokes that he and the monkey are “old friends,” but if the characters ask him to come with them to fight Strahd, he politely declines. If the characters tell him about the tarokka reading, Blinsky admits that he acquired the monkey from a half-elf carnival ringmaster named Rictavio.",
      "Tarokka_Card_URL": "Artifact.jpg",
      "Rank": "",
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "Joker1.png",
      "Playing_Card_Suit": "",
      "Index": 52,
      "Fortune2": "",
      "Result2": ""
    },
    {
      "Tarokka_Name": "Horseman",
      "Fortune": "I see a dead man of noble birth, guarded by his widow. Return life to the dead man’s corpse, and he will be your staunch ally.",
      "Result": "This card refers to Nikolai Wachter the elder, who is dead (see chapter 5, area N4o). If the characters cast a raise dead spell or a resurrection spell on his preserved corpse, Nikolai (LN male human noble) agrees to help the characters once he feels well enough, despite his wife’s protests. Although his family has long supported Strahd, Nikolai came to realize toward the end of his life that Strahd must be destroyed to save Barovia. If the characters don’t have the means to raise Nikolai from the dead, Rictavio (see appendix D) gives them a spell scroll of raise dead if he learns of their need. If they’re staying at the Blue Water Inn, he leaves the scroll in one of their rooms.",
      "Tarokka_Card_URL": "Horseman.jpg",
      "Rank": "",
      "Tarokka_Card_Suit": "",
      "Playing_Card_URL": "Joker2.png",
      "Playing_Card_Suit": "",
      "Index": 53,
      "Fortune2": "A man of death named Arrigal will forsake his dark lord to serve your cause. Beware! He has a rotten soul.",
      "Result2": "This card refers to the Vistani assassin Arrigal (see chapter 5, area N9c). If the characters mention this card reading to him, he accepts his fate and accompanies them. If the characters succeed in defeating Strahd, Arrigal betrays and attacks them, believing that he is destined to become Barovia’snew lord."
    }
  ]