let cardDescriptions = {
    "1 11": "The treasure lies in a dragon’s house, in hands once clean and now corrupted.",
    "2 11": "The treasure you seek is hidden behind the sun, in the house of a saint.",
    "2 1": "I see the skeleton of a deadly warrior, lying on a bed of stone flanked by gargoyles.",
    "1 1": "Go to a place of dizzying heights, where the stone itself is alive!",
    "1 2": "Look to the one who sees all. The treasure is hidden in her camp.",
    "2 12": "I see a garden dusted with snow, watched over by a scarecrow with a sackcloth grin. Look not to the garden but to the guardian.",
    "1 12": "I see a sleeping prince, a servant of light and the brother of darkness. The treasure lies with him.",
    "2 2": "Look to a place where sickness and madness are bred. Where children once cried, the treasure lies still.",
    "1 3": "I see a kneeling woman — a rose of great beauty plucked too soon. The master of the marsh knows of whom I speak.",
    "2 13": "Look to the west. Find a pool blessed by the light of the white sun.",
    "1 13": "Go to the mountains. Climb the white tower guarded by golden knights.",
    "2 3": "Look to the wizard of wines! In wood and sand the treasure hides.",
    "1 4": "I see a fallen house guarded by a great stone dragon. Look to the highest peak.",
    "1 14": "The thing you seek lies with the dead, under mountains of gold coins.",
    "2 4": "Seek a cask that once contained the finest wine, of which not a drop remains.",
    "2 14": "Find the mother — she who gave birth to evil.",
    "2 15": "An evil tree grows atop a hill of graves where the ancient dead sleep. The ravens can help you find it. Look for the treasure there.",
    "1 5": "The treasure is hidden in a small castle beneath a mountain, guarded by amber giants.",
    "2 5": "I see a dark room full of bottles. It is the tomb of a guild member.",
    "1 15": "Look for a den of wolves in the hills overlooking a mountain lake. The treasure belongs to Mother Night.",
    "1 6": "Search for the crypt of a wizard ordinaire. His staff is the key.",
    "2 16": "I see walls of bones, a chandelier of bones, and a table of bones — all that remains of enemies long forgotten.",
    "2 6": "A wounded elf has what you seek. He will part with the treasure to see his dark dreams fulfilled.",
    "1 16": "Find the Mad Dog’s crypt. The treasure lies within, beneath blackened bones.",
    "2 17": "I see a lonely mill on a precipice. The treasure lies within.",
    "1 17": "I see a faceless god. He awaits you at the end of a long and winding road, deep in the mountains.",
    "1 7": "A man is not what he seems. He comes here in a carnival wagon. Therein lies what you seek.",
    "2 7": "What you seek lies at the crossroads of life and death, among the buried dead.",
    "2 18": "What you seek lies in a pile of treasure, beyond a set of amber doors.",
    "1 18": "I see a throne fit for a king.",
    "1 8": "A woman hangs above a roaring fire. Find her, and you will find the treasure.",
    "2 8": "The Vistani have what you seek. A missing child holds the key to the treasure’s release.",
    "1 9": "I see a dead village, drowned by a river, ruled by one who has brought great evil into the world.",
    "2 9": "Look for a fortress inside a fortress, in a place hidden behind fire.",
    "1 19": "There is a town where all is not well. There you will find a house of corruption, and within, a dark room full of still ghosts.",
    "2 19": "Look for a wealthy woman. A staunch ally of the devil, she keeps the treasure under lock and key, with the bones of an ancient enemy.",
    "3 13": "Look for an entertaining man with a monkey. This man is more than he seems.",
    "3 7": "A werewolf holds a secret hatred for your enemy. Use her hatred to your advantage.",
    "3 9": ["Your greatest ally will be a wizard. His mind is broken, but his spells are strong.", "I see a man of faith whose sanity hangs by a thread. He has lost someone close to him."],
    "3 6": "Ah, the worst of all truths: You must face the evil of this land alone!",
    "3 3": ["Search for a troubled young man surrounded by wealth and madness. His home is his prison.", "Find a girl driven to insanity, locked in the heart of her dead father’s house. Curing her madness is key to your success."],
    "3 4": "Seek out the brother of the devil’s bride. They call him “the lesser,” but he has a powerful soul.",
    "3 12": ["I see a fallen paladin of a fallen order of knights. He lingers like a ghost in a dead dragon’s lair.", "Stir the spirit of the clumsy knight whose crypt lies deep within the castle."],
    "3 14": ["I see a dead man of noble birth, guarded by his widow. Return life to the dead man’s corpse, and he will be your staunch ally.", "A man of death named Arrigal will forsake his dark lord to serve your cause. Beware! He has a rotten soul."],
    "3 11": ["I see a young man with a kind heart. A mother’s boy! He is strong in body but weak of mind. Seek him out in the village of Barovia.", "Evil’s bride is the one you seek!"],
    "3 10": ["What horror is this? I see a man made by a man. Ageless and alone, it haunts the towers of the castle.", "Look for a man of music, a man with two heads. He lives in a place of great hunger and sorrow."]    ,
    "3 5": "A Vistana wanders this land alone, searching for her mentor. She does not stay in one place for long. Seek her out at Saint Markovia’s abbey, near the mists.",
    "2 20": "You will find what you seek in the castle, amid the ruins of a place of supplication.",
    "3 2": "Find the leader of the feathered ones who live among the vines. Though old, he has one more fight left in him.",
    "2 10": "I see a nest of ravens. There you will find the prize.",
    "3 1": "Look for a dusk elf living among the Vistani. He has suffered a great loss and is haunted by dark dreams. Help him, and he will help you in return.",
    "3 8": ["I see a child — a Vistana. You must hurry, for her fate hangs in the balance. Find her at the lake!", "I hear a wedding bell, or perhaps a death knell. It calls thee to a mountainside abbey, wherein you will find a woman who is more than the sum of her parts."],
    "1 20": "That which you seek lies in the womb of darkness, the devil’s lair: the one place to which he must return.",
    "1 10": "Look for a wizard’s tower on a lake. Let the wizard’s name and servant guide you to that which you seek."
}

let cardResults = {
    "1 11": "The treasure is in the possession of Vladimir Horngaard in Argynvostholt (chapter 7, area Q36).",
    "2 11": "The treasure lies in the main hall of the Abbey of Saint Markovia (chapter 8, area S13).",
    "2 1": "The treasure lies in the crypt of Endorovich (chapter 4, area K84, crypt 7).",
    "1 1": "The treasure lies in Castle Ravenloft’s north tower peak (chapter 4, area K60).",
    "1 2": "The treasure lies in Madam Eva’s encampment (chapter 2, area G). If she is the one performing the card reading, she says, “I think the treasure is under my very nose!”",
    "2 12": "The treasure is hidden inside one of the scarecrows in the garden of the Abbey of Saint Markovia (chapter 8, area S9).",
    "1 12": "I see a sleeping prince, a servant of light and the brother of darkness. The treasure lies with him.",
    "2 2": "Look to a place where sickness and madness are bred. Where children once cried, the treasure lies still.",
    "1 3": "I see a kneeling woman — a rose of great beauty plucked too soon. The master of the marsh knows of whom I speak.",
    "2 13": "Look to the west. Find a pool blessed by the light of the white sun.",
    "1 13": "Go to the mountains. Climb the white tower guarded by golden knights.",
    "2 3": "Look to the wizard of wines! In wood and sand the treasure hides.",
    "1 4": "I see a fallen house guarded by a great stone dragon. Look to the highest peak.",
    "1 14": "The thing you seek lies with the dead, under mountains of gold coins.",
    "2 4": "Seek a cask that once contained the finest wine, of which not a drop remains.",
    "2 14": "Find the mother — she who gave birth to evil.",
    "2 15": "An evil tree grows atop a hill of graves where the ancient dead sleep. The ravens can help you find it. Look for the treasure there.",
    "1 5": "The treasure is hidden in a small castle beneath a mountain, guarded by amber giants.",
    "2 5": "I see a dark room full of bottles. It is the tomb of a guild member.",
    "1 15": "Look for a den of wolves in the hills overlooking a mountain lake. The treasure belongs to Mother Night.",
    "1 6": "Search for the crypt of a wizard ordinaire. His staff is the key.",
    "2 16": "I see walls of bones, a chandelier of bones, and a table of bones — all that remains of enemies long forgotten.",
    "2 6": "A wounded elf has what you seek. He will part with the treasure to see his dark dreams fulfilled.",
    "1 16": "Find the Mad Dog’s crypt. The treasure lies within, beneath blackened bones.",
    "2 17": "I see a lonely mill on a precipice. The treasure lies within.",
    "1 17": "I see a faceless god. He awaits you at the end of a long and winding road, deep in the mountains.",
    "1 7": "A man is not what he seems. He comes here in a carnival wagon. Therein lies what you seek.",
    "2 7": "What you seek lies at the crossroads of life and death, among the buried dead.",
    "2 18": "What you seek lies in a pile of treasure, beyond a set of amber doors.",
    "1 18": "I see a throne fit for a king.",
    "1 8": "A woman hangs above a roaring fire. Find her, and you will find the treasure.",
    "2 8": "The Vistani have what you seek. A missing child holds the key to the treasure’s release.",
    "1 9": "I see a dead village, drowned by a river, ruled by one who has brought great evil into the world.",
    "2 9": "Look for a fortress inside a fortress, in a place hidden behind fire.",
    "1 19": "There is a town where all is not well. There you will find a house of corruption, and within, a dark room full of still ghosts.",
    "2 19": "Look for a wealthy woman. A staunch ally of the devil, she keeps the treasure under lock and key, with the bones of an ancient enemy.",
    "3 13": "Look for an entertaining man with a monkey. This man is more than he seems.",
    "3 7": "A werewolf holds a secret hatred for your enemy. Use her hatred to your advantage.",
    "3 9": ["Your greatest ally will be a wizard. His mind is broken, but his spells are strong.", "I see a man of faith whose sanity hangs by a thread. He has lost someone close to him."],
    "3 6": "Ah, the worst of all truths: You must face the evil of this land alone!",
    "3 3": ["Search for a troubled young man surrounded by wealth and madness. His home is his prison.", "Find a girl driven to insanity, locked in the heart of her dead father’s house. Curing her madness is key to your success."],
    "3 4": "Seek out the brother of the devil’s bride. They call him “the lesser,” but he has a powerful soul.",
    "3 12": ["I see a fallen paladin of a fallen order of knights. He lingers like a ghost in a dead dragon’s lair.", "Stir the spirit of the clumsy knight whose crypt lies deep within the castle."],
    "3 14": ["I see a dead man of noble birth, guarded by his widow. Return life to the dead man’s corpse, and he will be your staunch ally.", "A man of death named Arrigal will forsake his dark lord to serve your cause. Beware! He has a rotten soul."],
    "3 11": ["I see a young man with a kind heart. A mother’s boy! He is strong in body but weak of mind. Seek him out in the village of Barovia.", "Evil’s bride is the one you seek!"],
    "3 10": ["What horror is this? I see a man made by a man. Ageless and alone, it haunts the towers of the castle.", "Look for a man of music, a man with two heads. He lives in a place of great hunger and sorrow."]    ,
    "3 5": "A Vistana wanders this land alone, searching for her mentor. She does not stay in one place for long. Seek her out at Saint Markovia’s abbey, near the mists.",
    "2 20": "You will find what you seek in the castle, amid the ruins of a place of supplication.",
    "3 2": "Find the leader of the feathered ones who live among the vines. Though old, he has one more fight left in him.",
    "2 10": "I see a nest of ravens. There you will find the prize.",
    "3 1": "Look for a dusk elf living among the Vistani. He has suffered a great loss and is haunted by dark dreams. Help him, and he will help you in return.",
    "3 8": ["I see a child — a Vistana. You must hurry, for her fate hangs in the balance. Find her at the lake!", "I hear a wedding bell, or perhaps a death knell. It calls thee to a mountainside abbey, wherein you will find a woman who is more than the sum of her parts."],
    "1 20": "That which you seek lies in the womb of darkness, the devil’s lair: the one place to which he must return.",
    "1 10": "Look for a wizard’s tower on a lake. Let the wizard’s name and servant guide you to that which you seek."
}